#!/usr/bin/env bash
#
# Setup script for claude-remote
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/bin"

echo "Claude Remote Setup"
echo "==================="
echo

# Create config.sh if it doesn't exist
if [[ ! -f "$SCRIPT_DIR/config.sh" ]]; then
    echo "Creating configuration..."
    echo

    # Prompt for values
    read -p "Remote SSH host (e.g., ubuntu@your-server.com): " REMOTE_HOST
    read -p "Remote directory (e.g., /home/ubuntu/Projects): " REMOTE_DIR
    read -p "Local mount point [~/Projects/remote]: " LOCAL_MOUNT
    LOCAL_MOUNT="${LOCAL_MOUNT:-$HOME/Projects/remote}"

    # Expand ~ in LOCAL_MOUNT
    LOCAL_MOUNT="${LOCAL_MOUNT/#\~/$HOME}"

    cat > "$SCRIPT_DIR/config.sh" << EOF
# Claude Remote Configuration
# Generated by setup.sh

REMOTE_HOST="$REMOTE_HOST"
REMOTE_DIR="$REMOTE_DIR"
LOCAL_MOUNT="$LOCAL_MOUNT"
EOF

    echo
    echo "✓ Configuration saved to config.sh"
else
    echo "✓ config.sh already exists"
    source "$SCRIPT_DIR/config.sh"
fi

echo

# Make scripts executable
chmod +x "$SCRIPT_DIR/scripts/"*.sh

# Create bin directory if needed
mkdir -p "$BIN_DIR"

# Create symlinks
echo "Creating symlinks in $BIN_DIR..."

ln -sf "$SCRIPT_DIR/scripts/claude-remote.sh" "$BIN_DIR/claude-remote"
ln -sf "$SCRIPT_DIR/scripts/mount-remote.sh" "$BIN_DIR/mount-remote"
ln -sf "$SCRIPT_DIR/scripts/unmount-remote.sh" "$BIN_DIR/unmount-remote"

echo "✓ claude-remote -> scripts/claude-remote.sh"
echo "✓ mount-remote -> scripts/mount-remote.sh"
echo "✓ unmount-remote -> scripts/unmount-remote.sh"

echo

# Check if ~/bin is in PATH
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo "⚠ Warning: $BIN_DIR is not in your PATH"
    echo "  Add this to your ~/.zshrc or ~/.bashrc:"
    echo "  export PATH=\"\$HOME/bin:\$PATH\""
    echo
fi

# Check dependencies
echo "Checking dependencies..."

if ! command -v sshfs &> /dev/null; then
    echo "⚠ sshfs not found. Install with:"
    echo "  brew install --cask fuse-t"
    echo "  brew install macos-fuse-t/cask/fuse-t-sshfs"
else
    echo "✓ sshfs installed"
fi

if ! command -v claude &> /dev/null; then
    echo "⚠ claude not found. Install Claude Code first."
else
    echo "✓ claude installed"
fi

echo

# Test SSH connection
echo "Testing SSH connection to $REMOTE_HOST..."
if ssh -o ConnectTimeout=5 -o BatchMode=yes "$REMOTE_HOST" "echo ok" &> /dev/null; then
    echo "✓ SSH connection works"
else
    echo "⚠ SSH connection failed. Make sure:"
    echo "  1. The host is reachable"
    echo "  2. SSH keys are set up (ssh-copy-id $REMOTE_HOST)"
fi

echo
echo "Setup complete!"
echo
echo "Usage:"
echo "  claude-remote          # Launch Claude with remote execution"
echo "  mount-remote           # Mount remote filesystem only"
echo "  unmount-remote         # Unmount remote filesystem"
